### ISSUE TITLE
Passing qss styles to the CountDownDockWidget

### ISSUE THREAD

**Issue by voodoobox** [ashmanix/obs-plugin-countdown#43]
Greetings!

Is there anyway we can pass qss style codes to the countdown widget via the OBS theme.qss ?
I'm customizing my own OBS theme but there are somethings I can not change in the widget dock window, like the background for instance.

Thanks!

**Comment by ashmanix** [comment]
The plugin should draw from the OBS theme. The issue is that because it is a dockable widget it uses different styling for the window background compared to the rest of the widgets that show on OBS. If you're able to find what part of the theme styles dockable widgets then you should hopefully be able to style the background of the countdown timer window.
