### ISSUE TITLE
Feature Request: Compact Timer View for Streamers

### ISSUE THREAD

**Issue by rez1-dev** [ashmanix/obs-plugin-countdown#92]
First, thank you for the incredible UI redesign. It's functional, intuitive, and looks great!

I'd like to suggest a small quality-of-life improvement for streamers using the timer for countdowns involving minutes and seconds.

### **Request:**
Allow the timer to display only the selected format while hiding unused elements.

For example, if I select minutes and seconds, the interface would show:
- **Timer display**: Two input boxes and a timer format of `00:00` (minutes:seconds) instead of the full `00:00:00:00` (days:hours:minutes:seconds).
- Show Controls: Start, Pause, Reset, and the Settings cog.
- Hide unnecessary UI elements to make the interface more compact.

The delete, move up/down option could also be omitted when there's only one timer, as it isn't essential.

### **Why this is useful:**
Streamers frequently use timers for simple purposes (e.g. countdown to stream start), and this optional compact view would:
1. Reduce visual clutter.
2. Save space in overlays or layouts.
3. Avoid confusion by removing unused fields.

This feature would significantly enhance usability for an everyday use case.

**Comment by ashmanix** [comment]
I've had a think about this and I'm happy to hide the buttons that aren't required when using one timer (delete, up/down). 

I'll still keep the period input boxes for all types because of the inconsistency of hiding some boxes based on selection and then the timer ID still shows the full time. 

The other issue is there might be scenario where someone wants to edit all fields and set a timer but only wants to show some field in text form which might be an outlier but having all the input fields available at all times stops that from being an issue. Also the UI will be harder to understand with say just two fields for hours and seconds as I've removed the field type labels for space.

**Comment by ashmanix** [comment]
For the sake of simplicity I want to keep them. I know they clutter the UI when only one timer is being used but it was the compromise I ended up with to allow for multiple timers. 

I actually flirted with the idea of having two different plugins, one for a single timer and another for multiple timers, but decided against it because it would involve a lot more time to maintain both rather than one.

**Comment by ashmanix** [comment]
Cool, if you're going to make changes to the code I'd go to `countdown-widget.cpp` and edit the `SetupCountdownWidgetUI` function to add the following lines:

```c++
	ui->playAllButton->hide();
	ui->stopAllButton->hide();
	ui->addTimerButton->hide();
```

This will hide the buttons and shouldn't affect any of the other logic. Today I will work on a change to hide the delete and up/down buttons when only one timer is in use. I'll also hide the stop all and play all buttons too while I'm at it. Then the only extra button shown will be the add timer button.
